# Metamong Mysql v8.0.25

-- DROP SCHEMA metamong;
CREATE SCHEMA if not exists metamong;
 
USE metamong;

CREATE TABLE if not exists Room(
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(40) NOT NULL,
max_population INT DEFAULT 0
) COLLATE='utf8mb4_0900_ai_ci' 
ENGINE=INNODB;

CREATE TABLE if NOT EXISTS Characters(
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(200)
) COLLATE='utf8mb4_0900_ai_ci'
ENGINE=INNODB;

CREATE TABLE if not exists User(
id INT PRIMARY KEY AUTO_INCREMENT,
room_id INT DEFAULT NULL,
email VARCHAR(50) UNIQUE,
password VARCHAR(100) DEFAULT NULL,
character_id INT DEFAULT NULL,
auth TINYINT DEFAULT 0,
nickname VARCHAR(20) UNIQUE,
name VARCHAR(40) NOT NULL,
state TINYINT DEFAULT 0,
tutorial TINYINT DEFAULT 0,
FOREIGN KEY(room_id) REFERENCES Room(id) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY(character_id) REFERENCES Characters(id) ON UPDATE CASCADE ON DELETE CASCADE
) 
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=INNODB;


CREATE TABLE if NOT EXISTS Message(
id INT PRIMARY KEY AUTO_INCREMENT,
sent_user_id INT,
recv_user_id INT,
title VARCHAR(300) DEFAULT NULL,
content VARCHAR(500) DEFAULT NULL,
create_at TIMESTAMP DEFAULT NULL,
is_read TINYINT DEFAULT 0,
FOREIGN KEY(sent_user_id) REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY(recv_user_id) REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE
) COLLATE='utf8mb4_0900_ai_ci'
ENGINE=INNODB;


CREATE TABLE if not exists Guest_Book(
id INT PRIMARY KEY AUTO_INCREMENT,
user_id INT DEFAULT NULL,
create_at TIMESTAMP DEFAULT NULL,
content VARCHAR(500) DEFAULT NULL,
FOREIGN KEY(user_id) REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE
) COLLATE='utf8mb4_0900_ai_ci'
ENGINE=INNODB;


CREATE TABLE if NOT EXISTS Education(
id INT PRIMARY KEY AUTO_INCREMENT,
duration TIMESTAMP DEFAULT NULL,
education VARCHAR(50) DEFAULT NULL
) COLLATE='utf8mb4_0900_ai_ci'
ENGINE=INNODB;


CREATE TABLE if NOT EXISTS Certificate(
id INT PRIMARY KEY AUTO_INCREMENT,
user_id INT,
education_id INT,
create_at TIMESTAMP DEFAULT NULL,
pass_time INT DEFAULT NULL,
is_educated TINYINT DEFAULT 0,
is_authenticated TINYINT DEFAULT 0,
FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (education_id) REFERENCES Education(id) ON DELETE CASCADE ON UPDATE CASCADE
) COLLATE='utf8mb4_0900_ai_ci'
ENGINE=INNODB;


CREATE TABLE if NOT EXISTS Mission(
id INT PRIMARY KEY AUTO_INCREMENT,
education_id INT,
ordering INT,
description VARCHAR(1000),
FOREIGN KEY (education_id) REFERENCES Education(id) ON DELETE CASCADE ON UPDATE CASCADE
) COLLATE='utf8mb4_0900_ai_ci'
ENGINE=INNODB;


CREATE TABLE if NOT EXISTS Firebase_Token(
id INT PRIMARY KEY AUTO_INCREMENT,
user_id INT,
token VARCHAR(300),
create_at TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE
) COLLATE='utf8mb4_0900_ai_ci'
ENGINE=INNODB;


CREATE TABLE if not exists Oauth_Provider(
id INT PRIMARY KEY AUTO_INCREMENT,
user_id INT,
provider_name VARCHAR(40),
FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE
) COLLATE='utf8mb4_0900_ai_ci'
ENGINE=INNODB;

insert into characters values (1,'Ch01.png'),(2,'Ch02.png'),(3,'Ch03.png'),(4,'Ch04.png'),(5,'Ch05.png'),(6,'Ch06.png'),(7,'Ch07.png'),(8,'Ch08.png'),(9,'Ch09.png'),(10,'Ch10.png'),(11,'Ch11.png'),(12,'Ch12.png'),(13,'Ch13.png'),(14,'Ch14.png'),(15,'Ch15.png'),(16,'Ch16.png'),(17,'Ch17.png'),(18,'Ch18.png'),(19,'Ch19.png'),(20,'Ch20.png');

insert into education values (1 ,180,'지진'),(2 ,180,'화재');

COMMIT;

# 이메일 인증, jwt 등 Redis DB 사용 
